### ISSUE TITLE
Text rendering  bugs

### ISSUE THREAD

**Issue by AbdullahRusi** [Tehreer/Tehreer-Cocoa#1]
السلام عليكم ورحمة الله وبركاته
جزاك الله خيراً
بارك الله فيكم

First of all i would like to thank you for  excellent work - existing library for Android is doing its job very well.
Congratulations with new Cocoa version!
Hope it will be improved and widely used in many good apps inshaa Allah

Meanwhile i quickly patched demo app for my use case and saw some glitches:
Update: bugs were fixed, thank you!

:white_check_mark: glyphs being disconnected with 5e1e7b8aa9d56ceb71b79a19033b8a45e2f893a6
:white_check_mark: text alignment with 9db0b68c5b847796cdf036173d4e44fd714cd27b
:white_check_mark: crash in line resolver with 92a67b83323c3800fe8da36be98972cf656015eb

good findings: already better than CoreText(it failed) when rendering
 ‎0623 ARABIC LETTER ALEF WITH HAMZA ABOVE
 ‎064E ARABIC FATHA
and
 ‎0623 ARABIC LETTER ALEF WITH HAMZA ABOVE
 ‎0652 ARABIC SUKUN
as seen with font 8

**Comment by mta452** [comment]
وعلکم السلام ورحمة اللہ وبرکاتة

Thanks for your kind words :)

I have checked the sample project. Can you test by changing the order of shadda and fatha? I'm pretty sure that this will fix the issue. As for the glyphs being disconnected, it could be due to a missing glyph. Can you try reproducing the same issue in android version?

**Comment by mta452** [comment]
Good news, the glyphs being disconnected issue has been fixed. It was occurring due to cluster not clipping properly.

**Comment by AbdullahRusi** [comment]
جزاك الله خيراً
Great! Thank you for fast fix

meanwhile i prepared patch for demo app in android version
with the same text file and similar approach (proved no disconnected glyphs bug)
it still could be useful for further testing and comparison
(goal - same text rendering on all platforms)
[AndroidDemoAppPatch.patch.zip](https://github.com/Tehreer/Tehreer-Cocoa/files/3866142/AndroidDemoAppPatch.patch.zip)

next thing i noticed:
on short strings text become left-aligned
for example in verse 68:4
(for long ones like 68:43 it's correct)
i would like force it to be right-aligned

added to attributed string extension ParagraphStyle
with
.alignment = right
and
.baseWritingDirection = .rightToLeft
no effect

and if i set alignment like this:
label.textAlignment = TextAlignment.right;
it seems ignored at the moment

if i define string like this:
let str = "\u{202B}"+lines[n];
this also has no effect

here is updated xcode project
[_patchedDemo.zip](https://github.com/Tehreer/Tehreer-Cocoa/files/3866429/_patchedDemo.zip)

**Comment by mta452** [comment]
The alignment issue is fixed. `ParagraphStyle` attribute is not yet supported.

**Comment by AbdullahRusi** [comment]
جزاك الله خيراً

Looking for a proper way to lazy load data and display it.
Found this tutorial https://matteomanferdini.com/uitableview/
(complete original code is [here](https://github.com/matteom/Quotes))
Replaced some labels with TLabel.
Here is patched xcode project
[Quotes.zip](https://github.com/Tehreer/Tehreer-Cocoa/files/3882756/Quotes.zip)

1) there is crash with some strings
in LineResolver.swift on line 175
in func:
visualRuns.insert(glyphRun, at: insertIndex)
Fatal error: Array index is out of range

to reproduce uncomment line 29 or 37 or 39(seems different)
in Quote.swift

Maybe i must escape them properly before sending them to TLabel
but in general it should not crash i think.

2) another problem with this setup is that
only part of string is showed at startup
(before scroll and update).

need some way to force showing strings completely

**Comment by mta452** [comment]
Both issues are fixed. But for the second one, a hacky approach is used. `UITableView` only uses two passes for `UILabel`. So I have added a `UILabel` inside the `TLabel` for calculating the intrinsic content size. Do let me know if you are aware of a better approach than this.

**Comment by AbdullahRusi** [comment]
جزاك الله خيراً

Thank you!

prepared another setup (based on same project)
maybe you have some tips for increasing perfomance or doing it another way

Here is patched xcode project
[Quotes.zip](https://github.com/Tehreer/Tehreer-Cocoa/files/3895155/Quotes.zip)

and just for reference  old version before those changes (at 92a67b83323c3800fe8da36be98972cf656015eb )
which is really hacky ))
see comments in cellForRowAt func in QuotesDataSource.swift
[Quotes_working_older.zip](https://github.com/Tehreer/Tehreer-Cocoa/files/3895163/Quotes_working_older.zip)

As for perfomance (for text rendering) [this project](https://sluglibrary.com/) seems best, unfortunately it's closed source
But it's described [here](http://jcgt.org/published/0006/02/02/) and [here is pdf of slides](http://terathon.com/i3d2018_lengyel.pdf)

**Comment by mta452** [comment]
I have looked at the slug project but rendering with GPU is a totally different paradigm. Maybe I can think of something like this in a future version.

As of now, performance can be improved by using the typesetters directly. So creating a typesetter in the constructor of `Quote` like following,
```swift
Typesetter(text: text, defaultAttributes: [
    .typeface: TypefaceManager.default.typeface(forTag: TypefaceTag.Font8)!,
    .typeSize: 35])`
```
and using it instead of `attributedText` on tehreer label would be much performant.

One other thing to try would be to set the initial properties of label in `awakeFromNib()`, so that these calls are not repeated. And lastly, running the application in release mode.

Please take the pull before trying this and let me know your feedback.

**Comment by AbdullahRusi** [comment]
جزاك الله خيراً
Thank you for tips

cleaned up code
pulled latest changes, build using release configuration
tried two variants:
 * define typessetter in cellForRowAt
[Quotes_typesetter.zip](https://github.com/Tehreer/Tehreer-Cocoa/files/3918777/Quotes_typesetter.zip)

perfomance is better than it was

* define typesetter in Qoute

if i use dataSource as usual it gives error on create typesetter: 
Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
if i define dataSource later it shows nothing
if i force showing text  it will dissappear if i move or click
(see code in QuotesViewController.swift)
here is xcode project
[Quotes_typesetter_precalc.zip](https://github.com/Tehreer/Tehreer-Cocoa/files/3918958/Quotes_typesetter_precalc.zip)

**Comment by mta452** [comment]
I have made a small tweak, which makes the scrolling a lot smoother.
For the second case, the crash could be due to the fonts not yet registered in the typeface manager.
I'll check the text disappearance issue soon.

**Comment by mta452** [comment]
While looking into the text disappearance issue, I have found that the behavior is similar even when the `TLabel` is removed. So maybe it could be due to something else.

**Comment by AbdullahRusi** [comment]
الحمد لله
Found solution:
wrote dataSource extension function to prepare typesetters

quite pleased with performance now - can scroll from start to end very quickly
here is updated xcode project
[Quotes_typesetter_precalc.zip](https://github.com/Tehreer/Tehreer-Cocoa/files/3935291/Quotes_typesetter_precalc.zip)

now to minimize startup times i need to step further: such as calculate once then reuse cached data.

**Comment by mta452** [comment]
The first version is published on cocoapods. I have added partial support for paragraph style. If you have any other feature request, please raise an issue.

I value your contributions and have added special thanks in readme :)
