### ISSUE TITLE
links in label don't work in demo app [bug]

### ISSUE THREAD

**Issue by AbdullahRusi** [Tehreer/Tehreer-Cocoa#2]
السلام عليكم ورحمة الله وبركاته

links in label don't work in demo app

using Xcode Version 11.1 (11A1027) and iOS simulator Version 11.1 (SimulatorApp-912.1 SimulatorKit-570.3 CoreSimulator-681.5.4)
with iOS 13.1

while working with the same setup using standard textView
for example using [this tutorial](https://www.hackingwithswift.com/example-code/system/how-to-make-tappable-links-in-nsattributedstring)

**Comment by mta452** [comment]
وعلکم السلام ورحمة اللہ وبرکاتة

I have added a `LinkableLabel` class in demo project and updated the custom label screen. So the issue has been fixed.
