### ISSUE TITLE
SwiftUI support for TLabel [new feature]

### ISSUE THREAD

**Issue by AbdullahRusi** [Tehreer/Tehreer-Cocoa#4]
السلام عليكم ورحمة الله وبركاته

looking forward i think this should be implemented at some stage.
using SwiftUI become popular and this feature will be nice to have in shaa Allah

i would like to test some SwiftUI variants for my word-by-word use case
something like [this gist](https://gist.github.com/zef/e48e44a3a673c36b5a0c3d0eefb676ce)

update: 
[here is](https://github.com/Tehreer/Tehreer-Cocoa/files/4172257/WordByWordSwiftUI.zip) prepared xcode project
I'm trying to use UIViewRepresentable protocol according to
[this](https://www.sofapps.it/en/swiftuiframeworkprogramming-6.html) and [that](https://www.swiftdevjournal.com/using-text-views-in-a-swiftui-app/) articles.
only some lines appeared on screen
please take a look at code, maybe i missed something obvious

**Comment by AbdullahRusi** [comment]
الحمد لله
i've found a way to show text using this setup.

[here](https://github.com/Tehreer/Tehreer-Cocoa/files/4232729/WordByWordSwiftUI.zip) is updated xcode project.

but i have some problems:

* black background which i fixed in makeUIView func: i have to use white background color, if i use .clear some glitches appear
* fixed predefined word width and height - i need a way to tranfser actual width and height from TLabel to .frame(width: self.width, height: self.height)
* wrong width when changing screen orientation to landscape and coming back

if you comment TLabel on lines 192-193 in ContentView and
uncomment theese lines:
194-198 and 203 to enable standard Text()

you can see it behaves well when moving slider and changing screen orientation

i would like TLabel do the same or better in shaa Allah

**Comment by mta452** [comment]
وعلکم السلام ورحمة اللہ وبرکاته

Sorry for late reply. `SwiftUI` is a relatively new framework and I have set iOS 8.0 to be the minimum target for the library.

Can you please check if these issues occur in a `UITableView` implementation. That would verify if the problems are in `TLabel`.

Lastly, maybe you can contribute the `SwiftUI` version of `TLabel` and raise a PR?

**Comment by AbdullahRusi** [comment]
السلام عليكم ورحمة الله وبركاته

الحمد لله

I've found a way to fix this setup by:

* precalculating width of words from typesetter using makeSimpleLine func
* sending needed width to CollectionView


now it's behaves similar to SwiftUI's Text()
when changing screen orientation.
you may set width by slider

[here](https://github.com/Tehreer/Tehreer-Cocoa/files/4534710/WordByWordSwiftUI.zip) is updated xcode project.

رمضان المبارك
