### ISSUE TITLE
Rendering performance

### ISSUE THREAD

**Issue by guidedways** [Tehreer/Tehreer-Cocoa#6]
I noticed you're using `CGImage` (and caching them) for actual rendering. In comparison, I've found `CGLayerRef` (created out of `UIImage` for example) even closer to the metal and faster to render than `CGImage`.

**Comment by mta452** [comment]
Can you share a code snippet how you achieved this?

**Comment by guidedways** [comment]
Sure. Something like this:


```swift
       let context: CGContext? =  ...
        let glyph: UIImage = ...
        
        let canvasSize = CGSize(width: CGFloat(roundf(Float(glyph?.size.width ?? 0.0))), height: CGFloat(roundf(Float(glyph?.size.height ?? 0.0))))
        
        var glyphLayer: CGLayer? = nil
        if let context = context {
          glyphLayer = CGLayer(context, size: canvasSize, auxiliaryInfo: nil)
        }
        
        let glyphContext = glyphLayer?.context
        
        // Flip the image to it's the right side up!
        glyphContext?.translateBy(x: 0, y: canvasSize.height)
        glyphContext?.scaleBy(x: 1.0, y: -1.0)
        
         //Draw the image into the layer context
        if let glyphImg = glyph?.cgImage {
          glyphContext?.draw(glyphImg, in: CGRect(x: 0.0, y: 0.0, width: canvasSize.width, height: canvasSize.height))
        }
        
        if let glyphLayer = glyphLayer {
          glyphCache.append(glyphLayer)
        }
```

**Comment by guidedways** [comment]
You can then later use a normal `CGContext` to draw the `CGLayer` like so:

```swift
if let glyphToDraw = ... cached CGLayer {
      cgContext?.draw(glyphToDraw, in: rect)
 }
```

**Comment by guidedways** [comment]
I found a related question on SO:

https://stackoverflow.com/questions/7560979/cgcontextdrawimage-is-extremely-slow-after-large-uiimage-drawn-into-it

**Comment by mta452** [comment]
Thanks for sharing the code snippet. I'm not sure if `CGLayer` would be a better choice. I have found this question where the author says it's not recommended anymore. https://stackoverflow.com/questions/21738909/cglayer-no-longer-recommended-is-this-the-general-consensus
Plus, alpha only images are being cached currently. And I have not worked with `CGLayer` so I don't know if it can contain transparent images.
By the way, your idea is interesting. So I would like to know more, like how did you find out about this project, which kind of your requirement did it fulfill, which part of it appealed to you?

**Comment by guidedways** [comment]
Can you get in touch? fahad@2doapp.com

**Comment by mta452** [comment]
I have created a branch named `develop_cglayer` with CGLayer support. Can you check if the performance is better now?

**Comment by mta452** [comment]
@guidedways I'm wondering if you're monitoring and can share your feedback.
@AbdullahRusi Can you check this as well?

**Comment by mta452** [comment]
Used `CGLayer` in `v2.0` for rendering.

**Comment by guidedways** [comment]
@mta452 👏  Sorry I couldn't find the time to try this out at my end, it's been very hectic. Glad to see this implemented. I'm sure you saw an improvement in performance?

**Comment by mta452** [comment]
Didn't exactly measure the performance, but I'm pretty sure that it must be faster. Thanks for your suggestion.
